/**
 * File: zodiacData.js
 * Description: Zodiac sign definitions, compatibility matrix, readings, and rating labels
 * Author: AI4Students
 * Created: 2025-01-20
 * Last Modified: 2025-01-20
 */

export const ZODIAC_SIGNS = [
  { name: 'Aries', symbol: '\u2648', element: 'Fire', startMonth: 3, startDay: 21, endMonth: 4, endDay: 19, traits: 'Bold, ambitious, energetic', dateRange: 'Mar 21 \u2013 Apr 19' },
  { name: 'Taurus', symbol: '\u2649', element: 'Earth', startMonth: 4, startDay: 20, endMonth: 5, endDay: 20, traits: 'Reliable, patient, devoted', dateRange: 'Apr 20 \u2013 May 20' },
  { name: 'Gemini', symbol: '\u264A', element: 'Air', startMonth: 5, startDay: 21, endMonth: 6, endDay: 20, traits: 'Curious, adaptable, witty', dateRange: 'May 21 \u2013 Jun 20' },
  { name: 'Cancer', symbol: '\u264B', element: 'Water', startMonth: 6, startDay: 21, endMonth: 7, endDay: 22, traits: 'Intuitive, sentimental, protective', dateRange: 'Jun 21 \u2013 Jul 22' },
  { name: 'Leo', symbol: '\u264C', element: 'Fire', startMonth: 7, startDay: 23, endMonth: 8, endDay: 22, traits: 'Confident, dramatic, warm-hearted', dateRange: 'Jul 23 \u2013 Aug 22' },
  { name: 'Virgo', symbol: '\u264D', element: 'Earth', startMonth: 8, startDay: 23, endMonth: 9, endDay: 22, traits: 'Analytical, practical, diligent', dateRange: 'Aug 23 \u2013 Sep 22' },
  { name: 'Libra', symbol: '\u264E', element: 'Air', startMonth: 9, startDay: 23, endMonth: 10, endDay: 22, traits: 'Diplomatic, gracious, fair-minded', dateRange: 'Sep 23 \u2013 Oct 22' },
  { name: 'Scorpio', symbol: '\u264F', element: 'Water', startMonth: 10, startDay: 23, endMonth: 11, endDay: 21, traits: 'Passionate, resourceful, magnetic', dateRange: 'Oct 23 \u2013 Nov 21' },
  { name: 'Sagittarius', symbol: '\u2650', element: 'Fire', startMonth: 11, startDay: 22, endMonth: 12, endDay: 21, traits: 'Adventurous, optimistic, philosophical', dateRange: 'Nov 22 \u2013 Dec 21' },
  { name: 'Capricorn', symbol: '\u2651', element: 'Earth', startMonth: 12, startDay: 22, endMonth: 1, endDay: 19, traits: 'Disciplined, ambitious, strategic', dateRange: 'Dec 22 \u2013 Jan 19' },
  { name: 'Aquarius', symbol: '\u2652', element: 'Air', startMonth: 1, startDay: 20, endMonth: 2, endDay: 18, traits: 'Independent, inventive, humanitarian', dateRange: 'Jan 20 \u2013 Feb 18' },
  { name: 'Pisces', symbol: '\u2653', element: 'Water', startMonth: 2, startDay: 19, endMonth: 3, endDay: 20, traits: 'Compassionate, artistic, intuitive', dateRange: 'Feb 19 \u2013 Mar 20' }
];

export const COMPATIBILITY_MATRIX = {
  Aries:       { Aries: 76, Taurus: 42, Gemini: 78, Cancer: 42, Leo: 93, Virgo: 38, Libra: 72, Scorpio: 50, Sagittarius: 93, Capricorn: 47, Aquarius: 78, Pisces: 55 },
  Taurus:      { Aries: 42, Taurus: 75, Gemini: 38, Cancer: 90, Leo: 55, Virgo: 90, Libra: 65, Scorpio: 88, Sagittarius: 30, Capricorn: 95, Aquarius: 42, Pisces: 85 },
  Gemini:      { Aries: 78, Taurus: 38, Gemini: 72, Cancer: 40, Leo: 82, Virgo: 48, Libra: 93, Scorpio: 35, Sagittarius: 82, Capricorn: 32, Aquarius: 90, Pisces: 45 },
  Cancer:      { Aries: 42, Taurus: 90, Gemini: 40, Cancer: 75, Leo: 45, Virgo: 78, Libra: 38, Scorpio: 94, Sagittarius: 30, Capricorn: 60, Aquarius: 35, Pisces: 98 },
  Leo:         { Aries: 93, Taurus: 55, Gemini: 82, Cancer: 45, Leo: 78, Virgo: 45, Libra: 88, Scorpio: 55, Sagittarius: 92, Capricorn: 35, Aquarius: 68, Pisces: 42 },
  Virgo:       { Aries: 38, Taurus: 90, Gemini: 48, Cancer: 78, Leo: 45, Virgo: 72, Libra: 55, Scorpio: 88, Sagittarius: 35, Capricorn: 92, Aquarius: 38, Pisces: 65 },
  Libra:       { Aries: 72, Taurus: 65, Gemini: 93, Cancer: 38, Leo: 88, Virgo: 55, Libra: 75, Scorpio: 55, Sagittarius: 72, Capricorn: 40, Aquarius: 90, Pisces: 48 },
  Scorpio:     { Aries: 50, Taurus: 88, Gemini: 35, Cancer: 94, Leo: 55, Virgo: 88, Libra: 55, Scorpio: 78, Sagittarius: 42, Capricorn: 72, Aquarius: 45, Pisces: 92 },
  Sagittarius: { Aries: 93, Taurus: 30, Gemini: 82, Cancer: 30, Leo: 92, Virgo: 35, Libra: 72, Scorpio: 42, Sagittarius: 76, Capricorn: 38, Aquarius: 85, Pisces: 50 },
  Capricorn:   { Aries: 47, Taurus: 95, Gemini: 32, Cancer: 60, Leo: 35, Virgo: 92, Libra: 40, Scorpio: 72, Sagittarius: 38, Capricorn: 76, Aquarius: 42, Pisces: 62 },
  Aquarius:    { Aries: 78, Taurus: 42, Gemini: 90, Cancer: 35, Leo: 68, Virgo: 38, Libra: 90, Scorpio: 45, Sagittarius: 85, Capricorn: 42, Aquarius: 74, Pisces: 55 },
  Pisces:      { Aries: 55, Taurus: 85, Gemini: 45, Cancer: 98, Leo: 42, Virgo: 65, Libra: 48, Scorpio: 92, Sagittarius: 50, Capricorn: 62, Aquarius: 55, Pisces: 76 }
};

export const COMPATIBILITY_READINGS = {
  'Aries-Leo': 'When fire meets fire, sparks fly! Aries and Leo share a magnetic chemistry built on mutual admiration and boundless energy. Together you\'re unstoppable \u2014 just remember to take turns in the spotlight.',
  'Aries-Sagittarius': 'Two adventurers who never run out of fuel. Aries and Sagittarius share a love of spontaneity, freedom, and bold ideas. This pairing thrives on excitement \u2014 just make sure you occasionally slow down to enjoy the moment.',
  'Taurus-Cancer': 'A warm, nurturing bond built on loyalty and comfort. Taurus brings stability while Cancer brings deep emotional understanding. Together you create a safe haven \u2014 but don\'t let comfort become complacency.',
  'Taurus-Capricorn': 'The power couple of the zodiac. Both grounded, ambitious, and deeply loyal. You build empires together \u2014 just remember to schedule some fun between all that hard work.',
  'Gemini-Libra': 'An intellectual match made in the stars. Both air signs thrive on conversation, ideas, and social connection. Together you\'re the life of every party \u2014 just make sure you also connect on a deeper emotional level.',
  'Cancer-Pisces': 'A deeply intuitive, almost psychic connection. These two water signs understand each other without words. The emotional depth here is unmatched \u2014 just be careful not to drown in feelings.',
  'Cancer-Scorpio': 'An intense, magnetic bond between two water signs who feel everything deeply. Trust takes time but once built, it\'s unbreakable. Passion runs deep \u2014 channel it wisely.',
  'Leo-Libra': 'A glamorous, harmonious pairing. Leo brings the fire and confidence; Libra brings grace and balance. Together you light up every room \u2014 just watch for ego clashes.',
  'Virgo-Capricorn': 'Two earth signs who speak the language of practicality and dedication. Together you build something real and lasting. Just remember that perfection is the enemy of happiness.',
  'Scorpio-Pisces': 'A mystical, deeply emotional connection. Both water signs, you share an almost telepathic understanding. This bond transcends the ordinary \u2014 trust the current and let it carry you.',
  'Aries-Aries': 'Double the fire, double the intensity! Two Aries together create an explosive, passionate dynamic. You push each other to be bolder \u2014 but learn when to stand down.',
  'Aries-Gemini': 'A lively, fast-paced connection full of wit and adventure. Aries brings the courage; Gemini brings the ideas. Together you\'re never bored \u2014 but commitment needs conscious effort.',
  'Aries-Aquarius': 'A dynamic duo of independence and innovation. You inspire each other to break boundaries and think differently. Freedom is your foundation \u2014 build trust within it.',
  'Aries-Libra': 'Opposites attract in this classic pairing. Aries is direct; Libra is diplomatic. Together you find balance \u2014 if you appreciate rather than resist your differences.',
  'Aries-Taurus': 'Fire meets earth \u2014 passionate but sometimes rocky. Aries craves action while Taurus wants stability. Compromise is key to making this unlikely pair work.',
  'Aries-Cancer': 'A challenging but growth-inspiring pairing. Aries\' boldness can overwhelm Cancer\'s sensitivity, but if you learn each other\'s language, something beautiful can emerge.',
  'Aries-Virgo': 'Different speeds, different styles. Aries leaps; Virgo plans. This pairing works when you respect each other\'s approach rather than trying to change it.',
  'Aries-Scorpio': 'Two intense, powerful personalities. The attraction is magnetic but so are the clashes. Channel your shared determination toward common goals for best results.',
  'Aries-Capricorn': 'Cardinal energy squared \u2014 both are natural leaders. Power struggles are real, but mutual respect for each other\'s ambition can forge a formidable partnership.',
  'Aries-Pisces': 'Fire and water create steam. Aries is direct; Pisces is dreamy. This works when Aries protects Pisces\' gentle nature and Pisces softens Aries\' edges.',
  'Taurus-Taurus': 'Double the devotion, double the stubbornness. Two Taurus together build a comfortable, loyal bond \u2014 just be willing to budge sometimes.',
  'Taurus-Gemini': 'Earth and air \u2014 stability meets restlessness. Taurus wants routine; Gemini craves variety. Finding middle ground is the challenge and the reward.',
  'Taurus-Leo': 'Both love luxury and the finer things, but clash on control. Taurus is steady; Leo is dramatic. Mutual appreciation of each other\'s strengths is essential.',
  'Taurus-Virgo': 'A harmonious earth-sign match. Practical, loyal, and grounded. You build a beautiful, stable life together \u2014 just don\'t forget to add some spontaneity.',
  'Taurus-Libra': 'Both ruled by Venus, you share a love of beauty and harmony. But Taurus is possessive while Libra is social. Balance your needs and this shines.',
  'Taurus-Scorpio': 'Opposites on the zodiac wheel but deeply attracted. Intense loyalty defines this bond. Trust is everything \u2014 once established, it\'s unbreakable.',
  'Taurus-Sagittarius': 'A free spirit meets a homebody. Sagittarius wants to explore; Taurus wants to nest. This pairing stretches both of you \u2014 growth isn\'t always comfortable.',
  'Taurus-Aquarius': 'Traditional meets unconventional. Taurus craves security; Aquarius craves freedom. This works when you celebrate rather than resist your differences.',
  'Taurus-Pisces': 'A gentle, nurturing pairing. Taurus provides stability; Pisces adds magic and imagination. Together you create a world that\'s both grounded and dreamy.',
  'Gemini-Gemini': 'Never a dull moment between two Geminis. Conversation flows endlessly, but depth can be elusive. Challenge each other to go beyond the surface.',
  'Gemini-Cancer': 'Head meets heart. Gemini lives in thoughts; Cancer lives in feelings. Bridge the gap with patience and both of you grow immensely.',
  'Gemini-Leo': 'A bright, entertaining pairing full of laughter and creativity. Gemini keeps Leo entertained; Leo gives Gemini the attention they crave. Just stay genuine.',
  'Gemini-Virgo': 'Both ruled by Mercury, you connect through intellect. But Gemini scatters while Virgo focuses. Learn from each other\'s approach to life.',
  'Gemini-Scorpio': 'Light meets depth. Gemini skims surfaces; Scorpio plunges deep. This pairing is challenging but transformative if both commit to understanding.',
  'Gemini-Sagittarius': 'Opposites who share a love of learning and adventure. Conversation never stops; curiosity never fades. Freedom and trust are this pair\'s magic ingredients.',
  'Gemini-Capricorn': 'Playful meets serious. Gemini\'s lightness can frustrate Capricorn\'s seriousness, but there\'s much to learn from each other if you stay open.',
  'Gemini-Aquarius': 'An electric intellectual connection between two air signs. Ideas flow freely and innovation thrives. The bond is mental first, emotional later \u2014 and that\'s okay.',
  'Gemini-Pisces': 'Both mutable signs, you\'re adaptable but can struggle with direction. Gemini communicates with words; Pisces with feelings. Learn each other\'s language.',
  'Cancer-Cancer': 'A deeply emotional bond between two nurturers. You understand each other\'s moods intuitively. Create space for individual growth alongside your shared sanctuary.',
  'Cancer-Leo': 'The carer meets the star. Cancer nurtures; Leo shines. This works beautifully when Leo recognises Cancer\'s quiet strength and Cancer celebrates Leo\'s fire.',
  'Cancer-Virgo': 'A thoughtful, caring combination. Both attentive to detail and devoted to loved ones. You create a harmonious life \u2014 just ease up on the worry.',
  'Cancer-Libra': 'Emotional depth meets social grace. Cancer craves security; Libra craves harmony. Finding common ground takes work but yields a beautiful balance.',
  'Cancer-Sagittarius': 'The homebody and the wanderer. Cancer wants roots; Sagittarius wants wings. This pairing demands extraordinary compromise but offers extraordinary growth.',
  'Cancer-Capricorn': 'Opposite signs who complete each other. Cancer provides the heart; Capricorn provides the foundation. Together you build something enduring and meaningful.',
  'Cancer-Aquarius': 'Emotion meets intellect. Cancer leads with feelings; Aquarius leads with ideas. It\'s an unusual match that works when both honour what the other brings.',
  'Leo-Leo': 'Two lions in one den \u2014 magnificent when united, explosive when at odds. Share the spotlight and celebrate each other\'s victories for true harmony.',
  'Leo-Virgo': 'Fire meets earth in a sometimes-tricky pairing. Leo craves praise; Virgo offers critique. Appreciate each other\'s gifts \u2014 confidence and precision make a strong team.',
  'Leo-Scorpio': 'Two powerful, fixed signs. The attraction is fierce, the battles fiercer. Mutual respect and vulnerability are the keys to unlocking this intense connection.',
  'Leo-Sagittarius': 'An electrifying fire-sign match! Both generous, playful, and love adventure. This pairing radiates warmth and joy \u2014 just keep the egos in check.',
  'Leo-Capricorn': 'The performer meets the strategist. Leo wants applause; Capricorn wants results. Together you can have both \u2014 if you respect each other\'s values.',
  'Leo-Aquarius': 'Opposite signs with a magnetic pull. Leo rules the heart; Aquarius rules the mind. This pairing is never boring \u2014 embrace the creative tension.',
  'Leo-Pisces': 'Fire and water, confidence and sensitivity. Leo protects; Pisces inspires. A tender connection that flourishes when Leo softens and Pisces strengthens.',
  'Virgo-Virgo': 'Two perfectionists together \u2014 your standards are sky-high. The attention to detail is unmatched. Just remember to celebrate what\'s right, not just fix what\'s wrong.',
  'Virgo-Libra': 'Both appreciate beauty and order but in different ways. Virgo is practical; Libra is idealistic. Together you refine and elevate each other.',
  'Virgo-Scorpio': 'A quietly powerful pairing. Both analytical, both loyal, both intense in their own way. Trust builds slowly but the foundation is rock-solid.',
  'Virgo-Sagittarius': 'The planner and the improviser. Virgo values precision; Sagittarius values freedom. This works when you focus on what you admire rather than what frustrates.',
  'Virgo-Aquarius': 'Logic meets innovation. Both intellectual but approach problems differently. Virgo refines; Aquarius disrupts. There\'s brilliance in this combination if you stay flexible.',
  'Virgo-Pisces': 'Opposite signs who are deeply drawn together. Virgo grounds Pisces\' dreams; Pisces softens Virgo\'s edges. A complementary pairing at its finest.',
  'Libra-Libra': 'Double the charm, double the indecision. Two Libras create a beautiful, harmonious world \u2014 but someone has to make the tough calls eventually.',
  'Libra-Scorpio': 'Grace meets intensity. Libra smooths; Scorpio deepens. An unlikely match that works when Libra embraces depth and Scorpio embraces lightness.',
  'Libra-Sagittarius': 'A fun-loving, social pairing. Both enjoy exploration \u2014 Libra through people, Sagittarius through places. Together you expand each other\'s horizons.',
  'Libra-Capricorn': 'Beauty meets ambition. Libra brings charm; Capricorn brings drive. A power couple in the making \u2014 if you can align your very different priorities.',
  'Libra-Aquarius': 'An air-sign dream team. Both intellectual, social, and idealistic. You spark each other\'s best ideas and champion each other\'s causes.',
  'Libra-Pisces': 'Both romantic and gentle, but in different ways. Libra seeks balance; Pisces seeks transcendence. Beautiful when it clicks, confusing when it doesn\'t.',
  'Scorpio-Scorpio': 'The most intense pairing in the zodiac. Two Scorpios together experience everything at maximum depth. Transform together or risk destroying what you build.',
  'Scorpio-Sagittarius': 'Depth meets breadth. Scorpio plunges deep; Sagittarius flies high. A transformative pairing that works when you give each other space to be yourselves.',
  'Scorpio-Capricorn': 'A power pairing of determination and ambition. Both strategic, both relentless. Together you can conquer anything \u2014 just make time for tenderness.',
  'Scorpio-Aquarius': 'Fixed signs with very different energies. Scorpio is emotional intensity; Aquarius is cerebral detachment. A challenging but potentially revolutionary match.',
  'Sagittarius-Sagittarius': 'Double the adventure, double the restlessness. Two Sagittarians together never stop exploring. Just remember \u2014 even wanderers need an anchor sometimes.',
  'Sagittarius-Capricorn': 'The optimist meets the realist. Sagittarius dreams big; Capricorn plans strategically. Together you balance vision with execution \u2014 different but complementary.',
  'Sagittarius-Aquarius': 'Two free spirits united by ideals and independence. Intellectual sparks fly constantly. This visionary pairing changes the world \u2014 one wild idea at a time.',
  'Sagittarius-Pisces': 'Both mutable, both searching for meaning. Sagittarius seeks truth through experience; Pisces through feeling. A spiritual connection that needs grounding.',
  'Capricorn-Capricorn': 'Two mountain goats climbing together. Unstoppable ambition, unshakeable loyalty. Just don\'t forget there\'s more to life than reaching the summit.',
  'Capricorn-Aquarius': 'Tradition meets revolution. Capricorn builds within the system; Aquarius wants to redesign it. Respect each other\'s approach and you\'ll accomplish great things.',
  'Capricorn-Pisces': 'Earth meets water in a surprisingly tender pairing. Capricorn provides structure; Pisces provides soul. Together you build dreams that actually come true.',
  'Aquarius-Aquarius': 'Two visionaries in perfect intellectual sync. You understand each other\'s need for space and independence. Add emotional warmth to complete the picture.',
  'Aquarius-Pisces': 'The innovator and the dreamer. Aquarius thinks; Pisces feels. An unconventional pairing that works when you embrace each other\'s unique wavelength.',
  'Pisces-Pisces': 'A deeply spiritual, almost otherworldly bond. Two Pisces swim together in emotional depths few can fathom. Beautiful but needs a reality anchor.'
};

export const RATING_LABELS = [
  { min: 90, max: 100, label: '\u2728 Soulmates! \u2728' },
  { min: 75, max: 89, label: '\u{1F4AB} Strong Bond' },
  { min: 60, max: 74, label: '\u{1F319} Promising Match' },
  { min: 45, max: 59, label: '\u2601\uFE0F It\'s Complicated' },
  { min: 30, max: 44, label: '\u{1F30A} Challenging Currents' },
  { min: 0, max: 29, label: '\u{1F525} Cosmic Friction' }
];
